repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: git@github.com:codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args: ["--ignore-words=.codespell-ignore", "--skip=\"./third_party,./build\""]
        exclude: ".*\\.pb.*"

  - repo: git@github.com:pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        additional_dependencies: ['clang-format==17.0.6']
        args: ["--style=file"]
        files: "\\.(cpp|hpp|cc|hh|c|h)$"

  - repo: git@github.com:cpplint/cpplint
    rev: 2.0.1
    hooks:
      - id: cpplint
        args: ["--filter=-whitespace/comments"]
        files: "\\.(cpp|cc|h|hpp)$"


  - repo: git@github.com:pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      # - id: cppcheck
      #   args: ["--enable=all", "--inconclusive", "--std=c++17", "--quiet"]
      #   exclude: "(third_party|build)/"
      - id: clang-tidy
        args: ["--quiet", "--extra-arg=-std=c++17"]
        files: "\\.(cpp|cc|cxx|c\\+\\+|C|h|hpp|hh|hxx|h\\+\\+)$"
