// Code generated by fin-protoc. DO NOT EDIT.
#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <iostream>


struct BasicPacket {
    int8_t fieldI8;
    int16_t fieldI16;
    int32_t fieldI32;
    int64_t fieldI64;
    std::string fieldChar;
    uint8_t fieldU8;
    uint16_t fieldU16;
    uint32_t fieldU32;
    uint64_t fieldU64;
    float fieldF32;
    double fieldF64;
    int8_t fieldI8List;
    int16_t fieldI16List;
    int32_t fieldI32List;
    int64_t fieldI64List;
    std::string fieldCharList;
    uint8_t fieldU8List;
    uint16_t fieldU16List;
    uint32_t fieldU32List;
    uint64_t fieldU64List;
    float fieldF32List;
    double fieldF64List;
};
