// Code generated by fin-protoc. DO NOT EDIT.
#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <iostream>


struct NestedPacket {
    SubPacket SubPacket;
    SubPacket SubPacketList;
     InerPacket;
};
