// Code generated by fin-protoc. DO NOT EDIT.
#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <iostream>


struct RootPacket {
    uint16_t MsgType;
    uint32_t PayloadLen;
    match Payload;
    int32_t Checksum;
};
