// Code generated by fin-protoc. DO NOT EDIT.
#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <iostream>


struct StringPacket {
    std::string fieldDynamicString;
    std::string fieldDynamicString1;
    std::string fieldFixedString1;
    std::string fieldFixedString10;
    std::string fieldDynamicStringList;
    std::string fieldDynamicString1List;
    std::string fieldFixedString1List;
    std::string fieldFixedString10List;
};
