// Code generated by fin-protoc. DO NOT EDIT.
#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <iostream>


struct SubPacket {
    uint32_t fieldU32;
    int16_t fieldI16List;
};
